### ISSUE TITLE
Alarm Panel Button Not Clickable in Pending State

### ISSUE THREAD

**Issue by amartin177** [hassio-addons/addon-home-panel#12]
# Problem/Motivation
I'm testing out home-panel as an alternative to HADashboard.  While testing it out, I noticed that when the alarm_control_panel button is unable to be clicked to bring up the alarm panel dialog.  This is problematic, as I have my alarm set to go into pending mode and play a warning tone if the alarm is set and any of my sensors go off (this is so if we forget to disarm the alarm before entering our home, we get 20 seconds to disarm it before the real siren goes off).

## Expected behavior
While in the pending state, the button should be clickable to bring up the keypad to be able to disarm the alarm.

## Actual behavior
The alarm panel button does nothing when pressed/clicked when in pending state.

## Steps to reproduce
Setup the alarm_control_panel to go into a pending state for X seconds for armed_home or armed_away states.
e.g.
```
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 0
    delay_time: 0
    disarm_after_trigger: false
    trigger_time: 10
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 5
      delay_time: 20
    armed_away:
      pending_time: 5  
      delay_time: 20    
```

- Set the alarm to armed home or armed away using home panel. 
- Trip one of your sensors.
- Watch the status on the alarm panel button change to pending.
- Attempt to click or press the alarm button to pull up the keypad dialog.

## Proposed changes
Allow the alarm panel button to be clicked in the pending state, bringing up the keypad dialog.  This will give users the ability to disarm the alarm while in a pending state.
